// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ophbdjxeoxvdhmbqjfao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9waGJkanhlb3h2ZGhtYnFqZmFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNTMzMzEsImV4cCI6MjA3MTkyOTMzMX0.H7jL6uONa-B-_krrj2kwe5ve0NB6xSMP91bdnRsnxdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});